import '../model/events_model.dart';

class EventsRepository {
  Future<List<EventItem>> getEvents() async {
    // Simulate API call
    await Future.delayed(const Duration(seconds: 1));
    
    return [
      EventItem(
        id: '1',
        title: 'Friendly Party',
        location: 'Bardessono - Yountville, CA',
        boothSize: '10*10',
        spaceNumber: '12',
        cost: '\$500',
        startTime: '2:00 PM',
        endTime: '6:00 PM',
        date: 'July 25',
        status: ['Pending', 'Paid'],
        category: 'Today',
      ),
      EventItem(
        id: '2',
        title: 'Friendly Party',
        location: 'Bardessono - Yountville, CA',
        boothSize: '10*10',
        spaceNumber: '12',
        cost: '\$500',
        startTime: '2:00 PM',
        endTime: '6:00 PM',
        date: 'July 25',
        status: ['Pending', 'Unpaid'],
        category: 'Today',
      ),
      EventItem(
        id: '3',
        title: 'Friendly Party',
        location: 'Bardessono - Yountville, CA',
        boothSize: '10*10',
        spaceNumber: '12',
        cost: '\$500',
        startTime: '2:00 PM',
        endTime: '6:00 PM',
        date: 'July 25',
        status: ['Pending', 'Paid'],
        category: 'Today',
      ),
      EventItem(
        id: '4',
        title: 'Friendly Party',
        location: 'Bardessono - Yountville, CA',
        boothSize: '10*10',
        spaceNumber: '12',
        cost: '\$500',
        startTime: '2:00 PM',
        endTime: '6:00 PM',
        date: 'July 25',
        status: ['Denied'],
        category: 'Today',
      ),
      EventItem(
        id: '5',
        title: 'Conference Event',
        location: 'San Francisco, CA',
        boothSize: '15*15',
        spaceNumber: '25',
        cost: '\$800',
        startTime: '9:00 AM',
        endTime: '5:00 PM',
        date: 'July 30',
        status: ['Approved', 'Paid'],
        category: 'Upcoming',
      ),
      EventItem(
        id: '6',
        title: 'Trade Show',
        location: 'Los Angeles, CA',
        boothSize: '20*20',
        spaceNumber: '45',
        cost: '\$1200',
        startTime: '10:00 AM',
        endTime: '6:00 PM',
        date: 'August 5',
        status: ['Pending', 'Unpaid'],
        category: 'Upcoming',
      ),
      EventItem(
        id: '7',
        title: 'Exhibition',
        location: 'San Diego, CA',
        boothSize: '12*12',
        spaceNumber: '18',
        cost: '\$600',
        startTime: '1:00 PM',
        endTime: '7:00 PM',
        date: 'July 15',
        status: ['Approved', 'Paid'],
        category: 'Past',
      ),
    ];
  }
}
